version: '3.9'

services:
  frontend:
    build: ./qr-code
    ports:
      - "3000:3000"
    working_dir: /qr-code
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  
      timeout: 10s
      retries: 5

  backend:
    container_name: api
    build: ./api
    ports:
      - "3002:3002"
    working_dir: /api
    command: npm run dev
    volumes: 
      - "./api/src:/app-api/src"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_PORT=3002
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB_NAME=api
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3002"] 
      timeout: 10s
      retries: 5

  database:
    image: mysql:8.0.21
    container_name: database
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE 

volumes:
  mysql-data:
